name: Docker Test Pipeline

on:
  push:
    branches:
      - main  # ou la branche que tu utilises pour tes tests
  pull_request:
    branches:
      - main  # ou la branche que tu utilises pour tes tests

jobs:
  test:
    runs-on: ubuntu-latest  # Utiliser l'image Ubuntu la plus récente pour l'exécution des jobs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Récupère ton code source

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  # Configure Docker Buildx pour pouvoir créer des images

    - name: Build Docker image
      run: |
        docker build -t mon-projet-test .  # Construire l'image Docker avec le tag 'mon-projet-test'

    - name: Run tests in Docker container
      run: |
        docker run --name mon-projet-test-container mon-projet-test  # Exécute les tests dans le conteneur
        docker rm mon-projet-test-container  # Supprimer le conteneur après exécution

    - name: Clean up Docker images
      run: docker system prune -f  # Nettoyage des images Docker pour éviter d'accumuler des ressources
